name: "CI"

on:
  [push, pull_request]

jobs:

  server:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
          cache: 'pip'
          cache-dependency-path: server/requirements.txt

      - name: apt-get
        run: |
          sudo apt-get update
          sudo apt-get -y install libxml2-dev libxmlsec1-dev libxmlsec1-openssl libexempi-dev

      - name: docker-compose
        run: docker-compose -f ../.travis-docker-compose.yml up -d

      - name: pip install
        run: |
            python -m pip install --upgrade pip wheel setuptools
            pip install -r dev-requirements.txt

      - run: flake8
      - run: nosetests tests
      - run: mypy .
      - run: python manage.py app:initialize_data

  client:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12.x
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      - run: npm ci || npm install
      - run: npm run build
