name: "CI"

on:
  [push, pull_request]

jobs:

  server:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: apt-get
        run: |
          sudo apt-get update
          sudo apt-get -y install libxml2-dev libxmlsec1-dev libxmlsec1-openssl libexempi-dev

      - name: docker-compose
        run: docker-compose -f ../.travis-docker-compose.yml up -d

      - name: pip install
        run: |
            python -m pip install --upgrade pip wheel setuptools
            pip install -r dev-requirements.txt

      - name: flake8
        run: flake8

      - name: nosetests
        run: nosetests tests

      - name: mypy
        run: mypy .

      - name: initialize data
        run: python manage.py app:initialize_data

  client:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm ci
        run: npm ci || npm install

      - name: build
        run: npm run build
